name: Smoke

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # OPTIONAL: seed your SQLite DB if your app expects data
      # - name: Seed DB
      #   env:
      #     DB_PATH: ./data/ci.sqlite
      #   run: |
      #     mkdir -p data
      #     npm run seed

      - name: Start API (background)
        env:
          NODE_ENV: production
          PORT: 3000
          DB_PATH: ./data/ci.sqlite
        run: |
          mkdir -p data
          node dist/index.js & echo $! > server.pid
          # brief initial wait; health step will loop
          sleep 2

      - name: Health check
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:3000/api/health > /dev/null; then
              echo "Health check OK"
              exit 0
            fi
            echo "Waiting for API... ($i)"
            sleep 1
          done
          echo "Health check failed"
          exit 1

      - name: Stop API
        if: always()
        run: |
          if [ -f server.pid ]; then
            # kill process group to ensure any children die too
            kill -- -$(cat server.pid) 2>/dev/null || true
          fi
